name: CI Spring Boot gestion-station-ski

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Clean and compile
        run: mvn clean compile

      - name: Run unit tests
        run: mvn test

      - name: Package jar
        run: mvn package

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: gestion-station-ski-jar
          path: target/*.jar
